<?php

return [
    'builds' => [
        [
            'slug' => 'phantom',
            'tone' => 'violet',
            'name' => 'Ігровий ПК "Phantom"',
            'gpu' => 'Nvidia RTX 4070 Super',
            'cpu' => 'AMD Ryzen 7 7700',
            'ram' => '32GB DDR5 6000 MHz',
            'storage' => 'SSD M.2 NVMe 1TB',
            'price' => '69 990 ₴',
            'fps_score' => 146,
        ],
        [
            'slug' => 'nova',
            'tone' => 'magenta',
            'name' => 'Ігровий ПК "Nova"',
            'gpu' => 'AMD Radeon RX 7800 XT',
            'cpu' => 'AMD Ryzen 7 7800X3D',
            'ram' => '32GB DDR5 6000 MHz',
            'storage' => 'SSD M.2 NVMe 1TB',
            'price' => '82 990 ₴',
            'fps_score' => 156,
        ],
        [
            'slug' => 'vector',
            'tone' => 'amber',
            'name' => 'Ігровий ПК "Vector"',
            'gpu' => 'Nvidia RTX 3060 12GB GDDR6',
            'cpu' => 'Ryzen 5 3600X / 3600 (в залежності від наявності) 6C/12T 4.4GHz',
            'ram' => '16GB DDR4 2666-3200MHz (в залежності від наявності)',
            'storage' => 'SSD 2.5 120GB + HDD 500GB',
            'price' => '61 990 ₴',
            'fps_score' => 116,
            'product_specs' => [
                ['icon' => 'gpu', 'label' => 'Відеокарта', 'value' => 'Nvidia RTX 3060 12GB GDDR6'],
                ['icon' => 'cpu', 'label' => 'Процесор', 'value' => 'Ryzen 5 3600X / 3600 (в залежності від наявності) 6C/12T 4.4GHz'],
                ['icon' => 'ram', 'label' => 'Оперативна пам\'ять', 'value' => '16GB DDR4 2666-3200MHz (в залежності від наявності)'],
                ['icon' => 'motherboard', 'label' => 'Материнська плата', 'value' => 'Asus B450M-K або якісні аналоги'],
                ['icon' => 'storage', 'label' => 'Накопичувач', 'value' => 'SSD 2.5 120GB + HDD 500GB'],
                ['icon' => 'case', 'label' => 'Корпус', 'value' => 'Як на фото або інші на вибір'],
                ['icon' => 'psu', 'label' => 'Блок живлення', 'value' => '600+ Ватт (лише якісні, з APFC)'],
            ],
        ],
        [
            'slug' => 'crystal',
            'tone' => 'peach',
            'name' => 'Ігровий ПК "Crystal"',
            'gpu' => 'Nvidia RTX 5070',
            'cpu' => 'AMD Ryzen 7 9700X',
            'ram' => '32GB DDR5 6400 MHz',
            'storage' => 'SSD M.2 NVMe 2TB',
            'price' => '94 990 ₴',
            'fps_score' => 168,
        ],
        [
            'slug' => 'storm',
            'tone' => 'emerald',
            'name' => 'Ігровий ПК "Storm"',
            'gpu' => 'AMD Radeon RX 7900 GRE',
            'cpu' => 'AMD Ryzen 5 9600X',
            'ram' => '32GB DDR5 6000 MHz',
            'storage' => 'SSD M.2 NVMe 1TB',
            'price' => '74 990 ₴',
            'fps_score' => 132,
        ],
        [
            'slug' => 'orbit',
            'tone' => 'violet',
            'name' => 'Ігровий ПК "Orbit"',
            'gpu' => 'Nvidia RTX 3060 12GB',
            'cpu' => 'Intel Core i5-13400F',
            'ram' => '16GB DDR4 3600 MHz',
            'storage' => 'SSD M.2 NVMe 1TB',
            'price' => '42 990 ₴',
            'fps_score' => 92,
        ],
        [
            'slug' => 'titan',
            'tone' => 'magenta',
            'name' => 'Ігровий ПК "Titan"',
            'gpu' => 'Nvidia RTX 5080',
            'cpu' => 'Intel Core i7-14700KF',
            'ram' => '32GB DDR5 7200 MHz',
            'storage' => 'SSD M.2 NVMe 2TB',
            'price' => '129 990 ₴',
            'fps_score' => 186,
        ],
        [
            'slug' => 'frost',
            'tone' => 'amber',
            'name' => 'Ігровий ПК "Frost"',
            'gpu' => 'Nvidia RTX 4070 Ti Super',
            'cpu' => 'AMD Ryzen 7 8700F',
            'ram' => '32GB DDR5 6000 MHz',
            'storage' => 'SSD M.2 NVMe 1TB',
            'price' => '78 990 ₴',
            'fps_score' => 138,
        ],
        [
            'slug' => 'pulse',
            'tone' => 'peach',
            'name' => 'Ігровий ПК "Pulse"',
            'gpu' => 'AMD Radeon RX 7700 XT',
            'cpu' => 'AMD Ryzen 5 7600',
            'ram' => '32GB DDR5 5600 MHz',
            'storage' => 'SSD M.2 NVMe 1TB',
            'price' => '58 990 ₴',
            'fps_score' => 108,
        ],
        [
            'slug' => 'atlas',
            'tone' => 'emerald',
            'name' => 'Ігровий ПК "Atlas"',
            'gpu' => 'Nvidia RTX 4090',
            'cpu' => 'AMD Ryzen 9 9950X',
            'ram' => '64GB DDR5 6400 MHz',
            'storage' => 'SSD M.2 NVMe 4TB',
            'price' => '189 990 ₴',
            'fps_score' => 238,
        ],
    ],
];
