<?php

return [
    'brand' => [
        'name' => 'Kondor',
        'label' => 'Kondor PC',
        'tagline' => 'Інтернет-магазин ігрових ПК та кастомних збірок',
        'phone' => '+380633631066',
        'phone_display' => '+38 (063) 363-10-66',
        'telegram' => 'https://t.me/kondor_channeI',
        'instagram' => 'https://www.instagram.com/kondor_pc/',
    ],
    'hero' => [
        'eyebrow' => 'Kondor Storefront',
        'title' => 'Продаж ПК, що виглядають як шоукар і працюють як бойова станція.',
        'subtitle' => 'Готові і кастомні збірки для 1080p, 1440p та 4K. Робимо акцент на чисту кабельну укладку, збалансоване охолодження і впізнаваний преміальний стиль.',
    ],
    'tiers' => [
        [
            'slug' => 'entry',
            'name' => '1080p Старт',
            'description' => 'Доступні конфігурації для кіберспорту та комфортного Full HD.',
        ],
        [
            'slug' => '1440p',
            'name' => '1440p Core',
            'description' => 'Найкращий баланс ціни, дизайну й FPS для сучасних AAA-ігор.',
        ],
        [
            'slug' => '4k',
            'name' => '4K / Creator',
            'description' => 'Преміальні машини для максимальної графіки, стриму й монтажу.',
        ],
    ],
    'categories' => [
        [
            'slug' => 'builds',
            'name' => 'Готові збірки',
            'description' => 'ПК для гри, стриму та роботи під ключ.',
            'section' => 'Комп’ютери',
        ],
        [
            'slug' => 'custom',
            'name' => 'Індивідуальні конфігурації',
            'description' => 'Підбір компонентів під бюджет, стиль та сценарій.',
            'section' => 'Комп’ютери',
        ],
        [
            'slug' => 'gpu',
            'name' => 'Відеокарти',
            'description' => 'RTX та Radeon для апгрейду чи нової збірки.',
            'section' => 'Комплектуючі',
        ],
        [
            'slug' => 'cpu',
            'name' => 'Процесори',
            'description' => 'Intel Core та AMD Ryzen для різних задач.',
            'section' => 'Комплектуючі',
        ],
        [
            'slug' => 'memory',
            'name' => 'ОЗП та накопичувачі',
            'description' => 'DDR4, DDR5 та NVMe SSD під швидкі системи.',
            'section' => 'Комплектуючі',
        ],
        [
            'slug' => 'boards',
            'name' => 'Материнські плати',
            'description' => 'Стабільна база з Wi-Fi, Bluetooth і запасом під апгрейд.',
            'section' => 'Комплектуючі',
        ],
        [
            'slug' => 'cases',
            'name' => 'Корпуси та охолодження',
            'description' => 'Airflow, скло, RGB та чистий cable management.',
            'section' => 'Комплектуючі',
        ],
        [
            'slug' => 'monitors',
            'name' => 'Монітори',
            'description' => 'Панелі для кіберспорту, стриму та 4K-контенту.',
            'section' => 'Монітори',
        ],
        [
            'slug' => 'peripherals',
            'name' => 'Периферія',
            'description' => 'Миші, клавіатури, гарнітури та аксесуари.',
            'section' => 'Периферія',
        ],
    ],
    'benefits' => [
        [
            'title' => 'Адаптовано під ваш сценарій',
            'text' => 'Підбираємо конфігурацію під AAA-геймінг, кіберспорт, стрим або монтаж без сліпих переплат.',
        ],
        [
            'title' => 'Акуратна збірка й тестування',
            'text' => 'Перед видачею кожен ПК проходить стрес-тести, перевірку температур та фінальне налаштування системи.',
        ],
        [
            'title' => 'Підтримка після покупки',
            'text' => 'Допомагаємо з апгрейдом, консультаціями та підказуємо, як витиснути максимум із вашої системи.',
        ],
    ],
    'workflow' => [
        [
            'step' => '01',
            'title' => 'Обговорюємо задачу',
            'text' => 'Telegram, Instagram або дзвінок. Визначаємо бюджет, ігри, роздільну здатність і бажаний стиль збірки.',
        ],
        [
            'step' => '02',
            'title' => 'Погоджуємо конфіг',
            'text' => 'Даємо зрозумілий список комплектуючих, пояснюємо чому саме вони, і пропонуємо апгрейди без нав’язування.',
        ],
        [
            'step' => '03',
            'title' => 'Збираємо і тестуємо',
            'text' => 'Налаштовуємо BIOS, драйвери, RGB-сценарії та перевіряємо температуру, шум і стабільність.',
        ],
        [
            'step' => '04',
            'title' => 'Передаємо готовий ПК',
            'text' => 'Ви отримуєте систему, готову до першого запуску, і канал зв’язку на випадок подальших питань.',
        ],
    ],
    'faqs' => [
        [
            'question' => 'Чи можна змінити конфігурацію готової збірки?',
            'answer' => 'Так. Ми залишили шаблон під кастомізацію: можна збільшити обсяг ОЗП, SSD, змінити відеокарту, корпус, охолодження або оформлення.',
        ],
        [
            'question' => 'Чи буде ПК готовий до роботи з коробки?',
            'answer' => 'Так. Для шаблону ми заклали той самий сценарій, який потім підтримає движок: тестування, драйвери, базове налаштування і консультація перед стартом.',
        ],
        [
            'question' => 'Чи адаптивний сайт для телефона?',
            'answer' => 'Так. Усі ключові сторінки спроєктовані mobile-first: меню, каталожні картки, продуктова сторінка та CTA-блоки коректно перебудовуються на смартфонах і планшетах.',
        ],
    ],
    'products' => [
        [
            'slug' => 'emerald',
            'name' => 'Kondor Emerald',
            'series' => '1440p Signature',
            'tier_slug' => '1440p',
            'badge' => 'Хіт сезону',
            'availability' => 'Готово до відправки за 1-3 дні',
            'price' => 68999,
            'old_price' => 73999,
            'cpu' => 'AMD Ryzen 7 7800X3D',
            'gpu' => 'GeForce RTX 5070 12GB',
            'memory' => '32GB DDR5 6000 MHz',
            'storage' => 'SSD M.2 NVMe 1TB Gen4',
            'tagline' => 'Витриманий баланс між яскравою вітриною компонентів, холодним характером і високим FPS у 1440p.',
            'intro' => 'Панорамна збірка для тих, хто хоче естетику Instagram-ready корпусу без компромісів у продуктивності.',
            'colors' => 'Чорний або білий корпус',
            'palette' => ['#22c55e', '#34d399', '#0f172a'],
            'hero_stats' => [
                ['label' => '1440p Ultra', 'value' => '120+ FPS'],
                ['label' => 'Шум', 'value' => 'Тихий профіль'],
                ['label' => 'Апгрейд', 'value' => 'AM5 + PCIe 4.0'],
            ],
            'specs' => [
                ['label' => 'Відеокарта', 'value' => 'Nvidia GeForce RTX 5070 12GB'],
                ['label' => 'Процесор', 'value' => 'AMD Ryzen 7 7800X3D 8/16'],
                ['label' => 'Оперативна пам’ять', 'value' => '32GB DDR5 6000 MHz'],
                ['label' => 'Материнська плата', 'value' => 'B650M з Wi-Fi та Bluetooth'],
                ['label' => 'Накопичувач', 'value' => 'SSD M.2 NVMe 1TB PCIe 4.0'],
                ['label' => 'Корпус', 'value' => 'Панорамний airflow-корпус з ARGB'],
                ['label' => 'Блок живлення', 'value' => '750W 80+ Gold'],
                ['label' => 'Охолодження', 'value' => 'Tower RGB / AIO на вибір'],
            ],
            'highlights' => [
                'Відчутно швидка в Story-driven AAA та змагальних шутерах у 1440p.',
                'Виглядає як преміальний шоукейс завдяки склу, RGB і чистій укладці кабелів.',
                'Залишає запас під майбутній апгрейд без перебудови всієї платформи.',
            ],
            'included' => [
                'Фінальне тестування стабільності та температур',
                'Базове налаштування системи й драйверів',
                'Консультація щодо апгрейду та периферії',
                'Підготовка під перший запуск і ігрові сервіси',
            ],
            'options' => [
                ['title' => 'Апгрейд пам’яті', 'value' => '64GB DDR5 6000 MHz'],
                ['title' => 'Більший SSD', 'value' => '2TB NVMe Gen4'],
                ['title' => 'Преміальне охолодження', 'value' => '240/360 мм AIO'],
                ['title' => 'Оформлення', 'value' => 'Black Edition / White Edition'],
            ],
            'gallery' => [
                ['title' => 'Showcase Front', 'text' => 'Панорамна фронтальна зона та ефектна підсвітка вентиляторів.'],
                ['title' => 'Cooling View', 'text' => 'Акцент на продув та спокійні температури під довгим навантаженням.'],
                ['title' => 'Cable Detail', 'text' => 'Чиста укладка кабелів та акуратна подача компонентів.'],
            ],
            'performance' => [
                ['game' => 'Cyberpunk 2077', 'fps' => '120+ FPS / 1440p High'],
                ['game' => 'CS2', 'fps' => '300+ FPS / 1440p Competitive'],
                ['game' => 'Warzone', 'fps' => '165+ FPS / 1440p'],
            ],
        ],
        [
            'slug' => 'onyx',
            'name' => 'Kondor Onyx',
            'series' => '1440p Creator',
            'tier_slug' => '1440p',
            'badge' => 'Для стриму',
            'availability' => 'Під збірку 2-4 дні',
            'price' => 62999,
            'old_price' => 66999,
            'cpu' => 'Intel Core i5-14600KF',
            'gpu' => 'GeForce RTX 4070 Super 12GB',
            'memory' => '32GB DDR5 6400 MHz',
            'storage' => 'SSD M.2 NVMe 1TB Gen4',
            'tagline' => 'Темна, стримана й дуже швидка конфігурація для гри, монтажу коротких роликів і стримінгу.',
            'intro' => 'Мінімалістичний корпус із контрастним підсвічуванням і запасом продуктивності для одночасної гри та роботи.',
            'colors' => 'Graphite Black',
            'palette' => ['#f59e0b', '#fb7185', '#111827'],
            'hero_stats' => [
                ['label' => '1440p', 'value' => 'Ultra + RT'],
                ['label' => 'Стрим', 'value' => 'NVENC Ready'],
                ['label' => 'Вигляд', 'value' => 'Stealth Build'],
            ],
            'specs' => [
                ['label' => 'Відеокарта', 'value' => 'Nvidia GeForce RTX 4070 Super 12GB'],
                ['label' => 'Процесор', 'value' => 'Intel Core i5-14600KF'],
                ['label' => 'Оперативна пам’ять', 'value' => '32GB DDR5 6400 MHz'],
                ['label' => 'Материнська плата', 'value' => 'B760 Wi-Fi'],
                ['label' => 'Накопичувач', 'value' => 'SSD 1TB Gen4'],
                ['label' => 'Корпус', 'value' => 'Mid-Tower з mesh-фронтом'],
                ['label' => 'Блок живлення', 'value' => '750W 80+ Gold'],
                ['label' => 'Охолодження', 'value' => 'Баштове dual-fan'],
            ],
            'highlights' => [
                'Надійний універсал для геймінгу та контенту.',
                'Темний зовнішній вигляд без візуального шуму.',
                'Добре почувається з QHD-моніторами на 165 Гц.',
            ],
            'included' => [
                'Стрес-тест CPU та GPU',
                'Профілі вентиляторів під тишу/баланс',
                'Налаштування XMP та базових драйверів',
                'Поради по апгрейду під стрим і монтаж',
            ],
            'options' => [
                ['title' => 'SSD +1TB', 'value' => 'Додатковий NVMe накопичувач'],
                ['title' => 'Capture-ready', 'value' => 'Апгрейд під стрим-сценарії'],
                ['title' => 'RGB Accent', 'value' => 'Можливість м’якого amber-підсвічування'],
                ['title' => 'Cooling', 'value' => '240 мм водяне охолодження'],
            ],
            'gallery' => [
                ['title' => 'Stealth Front', 'text' => 'Чітка геометрія, темний графіт і точкові світлові акценти.'],
                ['title' => 'Airflow Core', 'text' => 'Стабільні температури при довгих сесіях.'],
                ['title' => 'Creator Setup', 'text' => 'Конфігурація з запасом під робочі задачі.'],
            ],
            'performance' => [
                ['game' => 'Apex Legends', 'fps' => '220+ FPS / 1440p'],
                ['game' => 'Alan Wake 2', 'fps' => '95+ FPS / 1440p DLSS'],
                ['game' => 'Valorant', 'fps' => '400+ FPS / 1440p'],
            ],
        ],
        [
            'slug' => 'arctic',
            'name' => 'Kondor Arctic',
            'series' => 'White Edition',
            'tier_slug' => '1440p',
            'badge' => 'White build',
            'availability' => 'Під замовлення 3-5 днів',
            'price' => 52999,
            'old_price' => 55999,
            'cpu' => 'AMD Ryzen 5 7500F',
            'gpu' => 'GeForce RTX 5060 Ti 16GB',
            'memory' => '32GB DDR5 6000 MHz',
            'storage' => 'SSD M.2 NVMe 1TB',
            'tagline' => 'Світла збірка з чистим акриловим настроєм, рівним RGB і комфортним запасом для 1440p.',
            'intro' => 'Підійде, якщо хочете ефектний white setup і не хочете переплачувати за преміум-флагмани.',
            'colors' => 'Snow White',
            'palette' => ['#38bdf8', '#f8fafc', '#94a3b8'],
            'hero_stats' => [
                ['label' => '1440p High', 'value' => '100+ FPS'],
                ['label' => 'Колір', 'value' => 'White RGB'],
                ['label' => 'Тиша', 'value' => 'Balanced'],
            ],
            'specs' => [
                ['label' => 'Відеокарта', 'value' => 'GeForce RTX 5060 Ti 16GB'],
                ['label' => 'Процесор', 'value' => 'AMD Ryzen 5 7500F'],
                ['label' => 'Оперативна пам’ять', 'value' => '32GB DDR5 6000 MHz'],
                ['label' => 'Материнська плата', 'value' => 'B650M White Edition'],
                ['label' => 'Накопичувач', 'value' => 'SSD 1TB NVMe'],
                ['label' => 'Корпус', 'value' => 'Панорамний white case'],
                ['label' => 'Блок живлення', 'value' => '650W 80+ Bronze/Gold'],
                ['label' => 'Охолодження', 'value' => 'ARGB tower cooler'],
            ],
            'highlights' => [
                'Легкий, чистий вигляд під білі столи та світлі сетапи.',
                'Хороший запас відеопам’яті для сучасних ігор та текстур.',
                'Зручний вхід у DDR5-платформу без надлишкового бюджету.',
            ],
            'included' => [
                'Перевірка RGB-сценаріїв і синхронізації',
                'Готовий профіль для повсякденного режиму',
                'Консультація щодо монітора та периферії',
                'Охайна кабельна укладка у білому сетапі',
            ],
            'options' => [
                ['title' => '2TB Storage', 'value' => 'Заміна на 2TB NVMe'],
                ['title' => 'AIO White', 'value' => 'Біле СВО 240 мм'],
                ['title' => 'Fan Pack', 'value' => 'Додаткові ARGB-вентилятори'],
                ['title' => 'Case Accent', 'value' => 'Mirror / Frosted style'],
            ],
            'gallery' => [
                ['title' => 'White Front', 'text' => 'Світла фронтальна подача без зайвого візуального шуму.'],
                ['title' => 'RGB Glow', 'text' => 'М’який холодний неон і дзеркальні відблиски.'],
                ['title' => 'Desk Fit', 'text' => 'Підходить під мінімалістичні світлі сетапи.'],
            ],
            'performance' => [
                ['game' => 'Fortnite', 'fps' => '200+ FPS / 1440p'],
                ['game' => 'Forza Horizon 5', 'fps' => '140+ FPS / 1440p'],
                ['game' => 'The Finals', 'fps' => '150+ FPS / 1440p'],
            ],
        ],
        [
            'slug' => 'blaze',
            'name' => 'Kondor Blaze',
            'series' => '4K Power',
            'tier_slug' => '4k',
            'badge' => 'Максимум FPS',
            'availability' => 'Преміум-збірка під замовлення',
            'price' => 81999,
            'old_price' => 85999,
            'cpu' => 'AMD Ryzen 7 9700X',
            'gpu' => 'Radeon RX 9070 XT 16GB',
            'memory' => '32GB DDR5 6400 MHz',
            'storage' => 'SSD M.2 NVMe 2TB',
            'tagline' => 'Потужна збірка з акцентом на чистий airflow і великий ресурс під 4K або важкі робочі задачі.',
            'intro' => 'Для тих, хто хоче безкомпромісний ПК із яскравим характером і довгим запасом актуальності.',
            'colors' => 'Charcoal / Ember',
            'palette' => ['#ef4444', '#f59e0b', '#1f2937'],
            'hero_stats' => [
                ['label' => '4K Ready', 'value' => 'High/Ultra'],
                ['label' => 'Storage', 'value' => '2TB NVMe'],
                ['label' => 'Cooling', 'value' => 'High Airflow'],
            ],
            'specs' => [
                ['label' => 'Відеокарта', 'value' => 'Radeon RX 9070 XT 16GB'],
                ['label' => 'Процесор', 'value' => 'AMD Ryzen 7 9700X'],
                ['label' => 'Оперативна пам’ять', 'value' => '32GB DDR5 6400 MHz'],
                ['label' => 'Материнська плата', 'value' => 'X870 / B650E класу'],
                ['label' => 'Накопичувач', 'value' => 'SSD 2TB NVMe'],
                ['label' => 'Корпус', 'value' => 'Airflow full glass tower'],
                ['label' => 'Блок живлення', 'value' => '850W 80+ Gold'],
                ['label' => 'Охолодження', 'value' => '360 мм AIO'],
            ],
            'highlights' => [
                'Відмінний варіант під 4K-геймінг та продуктивні робочі задачі.',
                'Масивний запас по живленню та охолодженню.',
                'Добре масштабується під майбутні апгрейди та периферію high-end класу.',
            ],
            'included' => [
                'Преміальний термоменеджмент і cable routing',
                'Підготовка під багатомоніторний сценарій',
                'Налаштування ігрових та робочих профілів',
                'Перевірка акустики й температур під тривалим навантаженням',
            ],
            'options' => [
                ['title' => '64GB Memory', 'value' => 'Апгрейд до 64GB DDR5'],
                ['title' => '4TB Storage', 'value' => 'Збільшення обсягу NVMe'],
                ['title' => 'Premium Board', 'value' => 'Розширений набір портів та VRM'],
                ['title' => 'Vertical GPU', 'value' => 'Вертикальна демонстрація відеокарти'],
            ],
            'gallery' => [
                ['title' => 'Power Front', 'text' => 'Глибокий контраст графіту й жарких акцентів.'],
                ['title' => 'Thermal Focus', 'text' => 'Продув і водяне охолодження під серйозне навантаження.'],
                ['title' => 'Premium Detail', 'text' => 'Побудований із запасом по живленню, місцю й airflow.'],
            ],
            'performance' => [
                ['game' => 'Black Myth: Wukong', 'fps' => '90+ FPS / 4K'],
                ['game' => 'Hogwarts Legacy', 'fps' => '110+ FPS / 1440p Ultra'],
                ['game' => 'Starfield', 'fps' => '85+ FPS / 4K'],
            ],
        ],
        [
            'slug' => 'nova',
            'name' => 'Kondor Nova',
            'series' => '1080p Start',
            'tier_slug' => 'entry',
            'badge' => 'Стартова',
            'availability' => 'Швидкий старт за 1-2 дні',
            'price' => 37999,
            'old_price' => 39999,
            'cpu' => 'AMD Ryzen 5 5600',
            'gpu' => 'GeForce RTX 4060 8GB',
            'memory' => '16GB DDR4 3600 MHz',
            'storage' => 'SSD M.2 NVMe 1TB',
            'tagline' => 'Раціональний вхід у світ сучасного геймінгу з охайним дизайном і можливістю подальшого росту.',
            'intro' => 'Підійде для кіберспорту, story-driven проєктів у 1080p та першого акуратного апгрейдного сетапу.',
            'colors' => 'Dark Slate',
            'palette' => ['#06b6d4', '#60a5fa', '#0f172a'],
            'hero_stats' => [
                ['label' => '1080p', 'value' => 'High / Ultra'],
                ['label' => 'Бюджет', 'value' => 'Раціонально'],
                ['label' => 'Апгрейд', 'value' => 'Готовий'],
            ],
            'specs' => [
                ['label' => 'Відеокарта', 'value' => 'GeForce RTX 4060 8GB'],
                ['label' => 'Процесор', 'value' => 'AMD Ryzen 5 5600'],
                ['label' => 'Оперативна пам’ять', 'value' => '16GB DDR4 3600 MHz'],
                ['label' => 'Материнська плата', 'value' => 'B550M'],
                ['label' => 'Накопичувач', 'value' => 'SSD 1TB NVMe'],
                ['label' => 'Корпус', 'value' => 'Airflow Mid Tower'],
                ['label' => 'Блок живлення', 'value' => '650W 80+ Bronze'],
                ['label' => 'Охолодження', 'value' => 'Ефективний tower cooler'],
            ],
            'highlights' => [
                'Комфортний Full HD-геймінг без зайвих витрат.',
                'Стриманий стиль і хороша продувність корпусу.',
                'Легка база для апгрейду до 32GB RAM чи сильнішої GPU.',
            ],
            'included' => [
                'Тест стабільності та охолодження',
                'Драйвери та базове налаштування',
                'Консультація щодо монітора 144/180 Гц',
                'Пояснення майбутніх апгрейдів',
            ],
            'options' => [
                ['title' => '32GB RAM', 'value' => 'Апгрейд до 32GB DDR4'],
                ['title' => 'Cooler Upgrade', 'value' => 'Тихіше повітряне охолодження'],
                ['title' => 'White Fans', 'value' => 'Додаткові світлові акценти'],
                ['title' => 'More Storage', 'value' => 'Плюс 1TB SSD'],
            ],
            'gallery' => [
                ['title' => 'Clean Front', 'text' => 'Стриманий вигляд без візуального перевантаження.'],
                ['title' => 'Entry Flow', 'text' => 'Продумана продувність і тиха щоденна робота.'],
                ['title' => 'Upgrade Base', 'text' => 'Хороша база для майбутніх покращень.'],
            ],
            'performance' => [
                ['game' => 'CS2', 'fps' => '280+ FPS / 1080p'],
                ['game' => 'Fortnite', 'fps' => '180+ FPS / 1080p'],
                ['game' => 'GTA V', 'fps' => '150+ FPS / 1080p'],
            ],
        ],
    ],
];
